north koreas ruling regime may have sent the most significant signal to date that it is willing to denuclearize on thursday , when it said it had blown up the punggye-ri nuclear testing site in the countrys mountainous northeast
but while closing down that site could end testing there , history shows that its nuclear legacy will likely endure for a very long time
just ask france , britain or the united states
after the brits tested a number of nuclear bombs in the southwestern australian outback during the mid-1950s , massive cleanup operations over the following two decades allegedly contaminated local workers
only now , over half a century after the tests , has the land been declared safe to be used once again
the united states similarly decided to forcibly relocate the inhabitants of bikini atoll in the pacific to conduct nuclear tests there in the 1940s
more than 100 miles away , the resettled bikini atoll natives were still exposed to radiation during the tests , and the u.s. government for decades faced accusations of failing to properly dismantle the testing site and decontaminate it
decades on , in the 1970s , the atolls food chain was still heavily contaminated and exposed some islanders who had returned to dangerous levels of cesium-137
many victims never received compensation from the united states or other nations that conducted dangerous nuclear weapons tests , including the soviet union and india
anger among residents there eventually erupted in the mid-1990s when thousands rioted on the largest island of french polynesia , tahiti , after a temporary stop on french tests was reversed
said faleomavaega , using rhetoric that would later become familiar in discussions about iran or north korea
in the late 1990s , france finally gave in to the pressure and decided to dismantle its testing site at the atoll of mururoa in french polynesia , an overseas collectivity that is composed of more than 100 islands in the south pacific
it remains unclear how successful those dismantlement and decontamination efforts really were especially because they were launched amid what critics say was a french coverup of the tests real extent
french media outlets later revealed that the more than 180 above- and underground tests there had contaminated a much larger area than paris previously admitted
medical examinations also showed that islands in the proximity of the test sites had disproportionately more cancer cases
the nuclear testing legacy haunts french officials until today
six years ago , australian media reported that the french government had concealed and hidden a 2010 warning that the fragile mururoa atoll could eventually collapse , potentially triggering a tsunami and exposing residents in french polynesia to dangerous radiation levels
many of the holes french researchers dug into the atoll are still radioactive and will remain so for centuries
roland oldham , the president of french polynesias nuclear association , told radio australia in 2012
the french government has gradually acknowledged its responsibility in disrupting french polynesias biotope and failing to properly dismantle the testing sites
in 2009 , france agreed to pay $ 80 million to rehabilitate another affected atoll in the south pacific , hao
but the long-term risks posed by frances tests at the atoll of mururoa may linger for decades
faleomavaega , the u.s. delegate , was already asking back in 1995
that question remains unanswered , even more than two decades on , and now it is something for north korea to think about , as well
